#!/usr/bin/env python3
"""
install.py — One-time installer for SYSOPS
Puts a 'sysops' launcher script in ~/.local/bin so you can
run it from anywhere just by typing: sysops
"""

import os, sys, stat, shutil
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
BIN_DIR    = Path.home() / ".local" / "bin"
LAUNCHER   = BIN_DIR / "sysops"

LAUNCHER_SCRIPT = f"""#!/usr/bin/env python3
# Auto-generated by sysops installer — do not edit manually
import sys
sys.path.insert(0, {str(SCRIPT_DIR)!r})
from sysops.__main__ import main
main()
"""

COLORS = {
    "green":  "\033[92m",
    "red":    "\033[91m",
    "yellow": "\033[93m",
    "cyan":   "\033[96m",
    "dim":    "\033[2m",
    "bold":   "\033[1m",
    "reset":  "\033[0m",
}
def c(col, t): return COLORS.get(col,"") + t + COLORS["reset"]

def main():
    print()
    print(c("bold", c("cyan", "  SYSOPS Installer")))
    print(c("dim",  "  ─────────────────────────────────────"))
    print()

    # Create ~/.local/bin if needed
    BIN_DIR.mkdir(parents=True, exist_ok=True)

    # Write launcher
    LAUNCHER.write_text(LAUNCHER_SCRIPT)
    LAUNCHER.chmod(LAUNCHER.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    print(c("green", f"  ✓ Launcher written to: {LAUNCHER}"))

    # Check if ~/.local/bin is on PATH
    path_dirs = os.environ.get("PATH","").split(":")
    if str(BIN_DIR) not in path_dirs:
        print()
        print(c("yellow", f"  ⚠ {BIN_DIR} is not in your PATH."))
        print(c("dim",    "  Add this to your ~/.bashrc or ~/.zshrc:\n"))
        print(c("cyan",   f'  export PATH="$HOME/.local/bin:$PATH"'))
        print()
        print(c("dim",    "  Then reload your shell:"))
        print(c("cyan",   "  source ~/.bashrc   # or ~/.zshrc"))
        print()
        print(c("dim",    "  After that, just type:  sysops"))
    else:
        print()
        print(c("green",  "  ✓ ~/.local/bin is already in PATH"))
        print()
        print(c("bold",   "  You can now launch SYSOPS from anywhere:"))
        print(c("cyan",   "    sysops"))

    print()
    print(c("dim", "  To uninstall, delete: " + str(LAUNCHER)))
    print()

    # Offer to run now
    try:
        ans = input(c("cyan", "  Launch SYSOPS now? [Y/n]: ")).strip().lower()
    except (EOFError, KeyboardInterrupt):
        ans = "n"

    if ans in ("", "y", "yes"):
        print()
        from sysops.__main__ import main as game_main
        game_main()

if __name__ == "__main__":
    # Make sure we can import sysops
    sys.path.insert(0, str(SCRIPT_DIR))
    main()
